version: 2

models:
    - name: uticen_calls_summary
      description: "metrics for uticen calls"
      config:
          enabled: true
          tags: uticen_calls
    - name: uticen_first_caller
      description: "uticen first calling agent"
      config:
          enabled: true
          tags: uticen_first_caller
    - name: uticen_login_count
      description: "client login count"
      config:
          enabled: true
          tags: uticen_login_count
    - name: uticen_clients_with_brand
      description: "uticen clients"
      config:
          enabled: true
          tags: uticen_clients_with_brand
    - name: uticen_transactions_with_brand
      description: "uticen transactions incl. incentives"
      config:
          enabled: true
          tags: uticen_transactions_with_brand
    - name: uticen_admin_users
      description: "uticen admin users"
      config:
          enabled: true
          tags: uticen_admin_users
    - name: uticen_agent_name_ftd
      description: "uticen agent name ftd"
      config:
          enabled: true
          tags: uticen_agent_name_ftd
    - name: uticen_agent_name_current
      description: "uticen agent name current"
      config:
          enabled: true
          tags: uticen_agent_name_current
    - name: uticen_agent_name_final
      description: "uticen agent name final"
      config:
          enabled: true
          tags: uticen_agent_name_final
    - name: uticen_ftd_date
      description: "uticen identifying the ftds"
      config:
          enabled: true
          tags: uticen_ftd_date
    - name: uticen_first_approved_date
      description: "uticen first deposit date"
      config:
          enabled: true
          tags: uticen_first_approved_date
    - name: uticen_first_approved_date_more_1k
      description: "uticen first deposit more than 1k"
      config:
          enabled: true
          tags: uticen_first_approved_date_more_1k
    - name: uticen_first_approved_date_less_1k
      description: "uticen first deposit less than 1k"
      config:
          enabled: true
          tags: uticen_first_approved_date_less_1k
    - name: uticen_agent_name_redepositor
      description: "uticen agent name redepositor"
      config:
          enabled: true
          tags: uticen_agent_name_redepositor
    - name: uticen_conversion_rate_denominator
      description: "uticen ftds details"
      config:
          enabled: true
          tags: uticen_conversion_rate_denominator
    - name: uticen_pv_numerator
      description: "uticen net amount details"
      config:
          enabled: true
          tags: uticen_pv_numerator
    - name: uticen_ftd_amount_buckets
      description: "uticen ftd buckets"
      config:
          enabled: true
          tags: uticen_ftd_amount_buckets
    - name: uticen_ftd_deposits
      description: "uticen ftd deposit details"
      config:
          enabled: true
          tags: uticen_ftd_deposits
    - name: uticen_non_ftd_deposits
      description: "uticen non ftd deposit details"
      config:
          enabled: true
          tags: uticen_non_ftd_deposits
    - name: uticen_non_ftd_deposits_yesterday
      description: "uticen non ftd deposit for yesterday details"
      config:
          enabled: true
          tags: uticen_non_ftd_deposits_yesterday
    - name: uticen_non_ftd_withdrawals
      description: "uticen non ftd withdrawal details"
      config:
          enabled: true
          tags: uticen_non_ftd_withdrawals
    - name: uticen_non_ftd_withdrawals_yesterday
      description: "uticen non ftd withdrawal for yesterday details"
      config:
          enabled: true
          tags: uticen_non_ftd_withdrawals
    - name: uticen_non_ftd_transactions
      description: "uticen non ftd transactions"
      config:
          enabled: true
          tags: uticen_non_ftd_transactions
    - name: uticen_non_ftd_total
      description: "uticen non ftd total"
      config:
          enabled: true
          tags: uticen_non_ftd_total
    - name: uticen_sales_depositors
      description: "uticen sales depositors report"
      config:
          enabled: true
          tags: uticen_sales_depositors
    - name: uticen_redepositor_amounts
      description: "uticen redepositor amounts"
      config:
          enabled: true
          tags: uticen_redepositor_amounts
    - name: uticen_summary_table
      description: "uticen summary table"
      config:
          enabled: true
          tags: uticen_summary_table
    - name: uticen_summary_agent
      description: "uticen summary for agents"
      config:
          enabled: true
          tags: uticen_summary_agent
    - name: uticen_campaign_table
      description: "uticen campaign table"
      config:
          enabled: true
          tags: uticen_campaign_table
    - name: uticen_chargeback_clients_transactions
      description: "uticen chargeback clients transactions"
      config:
          enabled: true
          tags: uticen_chargeback_clients_transactions
    - name: uticen_total_client_sum_zero
      description: "uticen clients with zero balance"
      config:
          enabled: true
          tags: uticen_total_client_sum_zero
    - name: uticen_refunded_clients_transactions
      description: "uticen clients with zero balance"
      config:
          enabled: true
          tags: uticen_refunded_clients_transactions
    - name: uticen_non_ftd_withdrawals_cb
      description: "uticen wds no refund or cb"
      config:
          enabled: true
          tags: uticen_non_ftd_withdrawals_cb
    - name: uticen_summary_calls
      description: "uticen summary calls table"
      config:
          enabled: true
          tags: uticen_summary_calls
    - name: uticen_max_call_date
      description: "uticen max call date"
      config:
          enabled: true
          tags: uticen_max_call_date
    - name: uticen_calls_count_all
      description: "uticen all calls count"
      config:
          enabled: true
          tags: uticen_calls_count_all
    - name: uticen_non_answering_clients_all
      description: "uticen all non answering clients"
      config:
          enabled: true
          tags: uticen_non_answering_clients_all
    - name: uticen_non_answering_pools
      description: "uticen non answering pools"
      config:
          enabled: true
          tags: uticen_non_answering_pools
    - name: uticen_redepositor_client
      description: "uticen redepositor client"
      config:
          enabled: true
          tags: uticen_redepositor_client
    - name: uticen_ta_with_brand
      description: "uticen trading account balances"
      config:
          enabled: true
          tags: uticen_ta_with_brand
    - name: uticen_ftds_yesterday
      description: "yesterdays ftds"
      config:
          enabled: true
          tags: uticen_ftds_yesterday
    - name: uticen_redepositor_amounts_atomix
      description: "uticen redepositor amounts for atomix"
      config:
          enabled: true
          tags: uticen_redepositor_amounts_atomix
    - name: uticen_clients_notes
      description: "uticen notes for clients"
      config:
          enabled: true
          tags: uticen_clients_notes
    - name: uticen_withdrawals_count_per_month
      description: "uticen counting wds per month"
      config:
          enabled: true
          tags: uticen_withdrawals_count_per_month
    - name: uticen_deposits_count
      description: "uticen counting deposits"
      config:
          enabled: true
          tags: uticen_deposits_count
    - name: uticen_calls_per_month
      description: "uticen calls per month for brazil"
      config:
          enabled: true
          tags: uticen_calls_per_month
    - name: uticen_active_agents
      description: "uticen active agents per month"
      config:
          enabled: true
          tags: uticen_active_agents
    - name: uticen_country_list
      description: "uticen country list with country codes"
      config:
          enabled: true
          tags: uticen_country_list
    - name: uticen_marketing_cat3
      description: "uticen prep model for cat3 marketing email"
      config:
          enabled: true
          tags: uticen_marketing_cat3
    - name: uticen_marketing_cat_1_4
      description: "uticen prep model for cat 1 and 4 marketing emails"
      config:
          enabled: true
          tags: uticen_marketing_cat_1_4
    - name: uticen_summary_client_amounts
      description: "uticen summary per client for amounts"
      config:
          enabled: true
          tags: uticen_summary_client_amounts
    - name: uticen_client_last_note
      description: "uticen last note for client"
      config:
          enabled: true
          tags: uticen_client_last_note



